### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by joewilloe** [pathwar/level-captcha#1]
I want to use [Sourcegraph](https://sourcegraph.com) for level-captcha code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/pathwar/level-captcha. (It should only take 30 seconds.)

Thank you!

**Comment by moul** [comment]
Hum, I think we will need your help :)

https://sourcegraph.com/github.com/pathwar/level-captcha/.builds/2254790
